-- 1. Create employee_loans table if not already created
CREATE TABLE IF NOT EXISTS public.employee_loans (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    employee_id TEXT NOT NULL,
    employee_pin TEXT,
    employee_name TEXT,
    employee_contact TEXT,
    loan_name TEXT NOT NULL,
    loan_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    monthly_deduction NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    months_duration INT DEFAULT 1,
    total_repaid NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    remaining_balance NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    status TEXT NOT NULL DEFAULT 'Pending',
    notes TEXT,
    start_date TIMESTAMPTZ,
    end_date TIMESTAMPTZ,
    selected_months JSONB,
    skipped_months JSONB,
    months_skipped INT DEFAULT 0,
    loan_tax_mode TEXT DEFAULT 'same',
    loan_tax_amount NUMERIC(12,2) DEFAULT 0.00,
    deduction_basis TEXT DEFAULT 'net_salary',
    last_payment_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Add any missing columns to existing employee_loans table
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'employee_loans' AND column_name = 'start_date') THEN
        ALTER TABLE public.employee_loans ADD COLUMN start_date TIMESTAMPTZ;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'employee_loans' AND column_name = 'end_date') THEN
        ALTER TABLE public.employee_loans ADD COLUMN end_date TIMESTAMPTZ;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'employee_loans' AND column_name = 'selected_months') THEN
        ALTER TABLE public.employee_loans ADD COLUMN selected_months JSONB;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'employee_loans' AND column_name = 'skipped_months') THEN
        ALTER TABLE public.employee_loans ADD COLUMN skipped_months JSONB;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'employee_loans' AND column_name = 'months_skipped') THEN
        ALTER TABLE public.employee_loans ADD COLUMN months_skipped INT DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'employee_loans' AND column_name = 'loan_tax_mode') THEN
        ALTER TABLE public.employee_loans ADD COLUMN loan_tax_mode TEXT DEFAULT 'same';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'employee_loans' AND column_name = 'loan_tax_amount') THEN
        ALTER TABLE public.employee_loans ADD COLUMN loan_tax_amount NUMERIC(12,2) DEFAULT 0.00;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'employee_loans' AND column_name = 'deduction_basis') THEN
        ALTER TABLE public.employee_loans ADD COLUMN deduction_basis TEXT DEFAULT 'net_salary';
    ELSE
        ALTER TABLE public.employee_loans ALTER COLUMN deduction_basis SET DEFAULT 'net_salary';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'employee_loans' AND column_name = 'last_payment_date') THEN
        ALTER TABLE public.employee_loans ADD COLUMN last_payment_date TIMESTAMPTZ;
    END IF;
END $$;

-- 3. Enable RLS and setup open access policies
ALTER TABLE public.employee_loans ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for authenticated users on employee_loans" ON public.employee_loans;
DROP POLICY IF EXISTS "Allow anon read/write on employee_loans" ON public.employee_loans;

CREATE POLICY "Allow all for authenticated users on employee_loans" 
ON public.employee_loans FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow anon read/write on employee_loans" 
ON public.employee_loans FOR ALL TO anon USING (true) WITH CHECK (true);

-- 4. Enable Supabase Realtime
DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.employee_loans;
EXCEPTION WHEN OTHERS THEN
    NULL;
END $$;


