-- ==============================================================================
-- COMPREHENSIVE SUPABASE SCHEMA FIX
-- Run this in your Supabase SQL Editor to fix 400 Bad Request errors across:
-- 1. employee_loans (all loan columns & deduction_basis)
-- 2. notifications (allowing 'admin' and string user_ids without UUID errors)
-- 3. shift_timings (adding missing fix hours & grace columns)
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. FIX EMPLOYEE_LOANS TABLE
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.employee_loans (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    employee_id TEXT NOT NULL,
    employee_pin TEXT,
    employee_name TEXT,
    employee_contact TEXT,
    loan_name TEXT NOT NULL,
    loan_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    monthly_deduction NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    months_duration INT DEFAULT 1,
    total_repaid NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    remaining_balance NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    status TEXT NOT NULL DEFAULT 'Pending',
    notes TEXT,
    start_date TIMESTAMPTZ,
    end_date TIMESTAMPTZ,
    selected_months JSONB,
    skipped_months JSONB,
    months_skipped INT DEFAULT 0,
    loan_tax_mode TEXT DEFAULT 'same',
    loan_tax_amount NUMERIC(12,2) DEFAULT 0.00,
    deduction_basis TEXT DEFAULT 'net_salary',
    last_payment_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'employee_loans' AND column_name = 'start_date') THEN
        ALTER TABLE public.employee_loans ADD COLUMN start_date TIMESTAMPTZ;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'employee_loans' AND column_name = 'end_date') THEN
        ALTER TABLE public.employee_loans ADD COLUMN end_date TIMESTAMPTZ;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'employee_loans' AND column_name = 'selected_months') THEN
        ALTER TABLE public.employee_loans ADD COLUMN selected_months JSONB;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'employee_loans' AND column_name = 'skipped_months') THEN
        ALTER TABLE public.employee_loans ADD COLUMN skipped_months JSONB;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'employee_loans' AND column_name = 'months_skipped') THEN
        ALTER TABLE public.employee_loans ADD COLUMN months_skipped INT DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'employee_loans' AND column_name = 'loan_tax_mode') THEN
        ALTER TABLE public.employee_loans ADD COLUMN loan_tax_mode TEXT DEFAULT 'same';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'employee_loans' AND column_name = 'loan_tax_amount') THEN
        ALTER TABLE public.employee_loans ADD COLUMN loan_tax_amount NUMERIC(12,2) DEFAULT 0.00;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'employee_loans' AND column_name = 'deduction_basis') THEN
        ALTER TABLE public.employee_loans ADD COLUMN deduction_basis TEXT DEFAULT 'net_salary';
    ELSE
        ALTER TABLE public.employee_loans ALTER COLUMN deduction_basis SET DEFAULT 'net_salary';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'employee_loans' AND column_name = 'last_payment_date') THEN
        ALTER TABLE public.employee_loans ADD COLUMN last_payment_date TIMESTAMPTZ;
    END IF;
END $$;

ALTER TABLE public.employee_loans ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all for authenticated users on employee_loans" ON public.employee_loans;
DROP POLICY IF EXISTS "Allow anon read/write on employee_loans" ON public.employee_loans;
CREATE POLICY "Allow all for authenticated users on employee_loans" ON public.employee_loans FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon read/write on employee_loans" ON public.employee_loans FOR ALL TO anon USING (true) WITH CHECK (true);
GRANT ALL ON public.employee_loans TO anon, authenticated, service_role;

-- ------------------------------------------------------------------------------
-- 2. FIX NOTIFICATIONS TABLE (Convert user_id to TEXT to allow 'admin' and IDs)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

DO $$
BEGIN
    -- Drop foreign key constraint on user_id if it exists
    ALTER TABLE public.notifications DROP CONSTRAINT IF EXISTS notifications_user_id_fkey;
    -- Alter user_id column to TEXT
    ALTER TABLE public.notifications ALTER COLUMN user_id TYPE TEXT USING user_id::TEXT;
EXCEPTION WHEN OTHERS THEN
    NULL;
END $$;

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all operations for notifications" ON public.notifications;
CREATE POLICY "Allow all operations for notifications" ON public.notifications FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.notifications TO anon, authenticated, service_role;

-- ------------------------------------------------------------------------------
-- 3. FIX SHIFT_TIMINGS TABLE
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.shift_timings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    grace_period_mins INT DEFAULT 15,
    is_fixed_hours BOOLEAN DEFAULT false,
    total_hours NUMERIC DEFAULT 9,
    applicable_days TEXT[],
    saturday_rule TEXT DEFAULT 'alternate',
    employee_ids TEXT[],
    is_default BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'shift_timings' AND column_name = 'is_fixed_hours') THEN
        ALTER TABLE public.shift_timings ADD COLUMN is_fixed_hours BOOLEAN DEFAULT false;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'shift_timings' AND column_name = 'total_hours') THEN
        ALTER TABLE public.shift_timings ADD COLUMN total_hours NUMERIC DEFAULT 9;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'shift_timings' AND column_name = 'grace_period_mins') THEN
        ALTER TABLE public.shift_timings ADD COLUMN grace_period_mins INT DEFAULT 15;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'shift_timings' AND column_name = 'saturday_rule') THEN
        ALTER TABLE public.shift_timings ADD COLUMN saturday_rule TEXT DEFAULT 'alternate';
    END IF;
END $$;

ALTER TABLE public.shift_timings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all operations for shift_timings" ON public.shift_timings;
CREATE POLICY "Allow all operations for shift_timings" ON public.shift_timings FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.shift_timings TO anon, authenticated, service_role;

-- ------------------------------------------------------------------------------
-- 4. REALTIME REPLICATION
-- ------------------------------------------------------------------------------
DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.employee_loans;
    ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
    ALTER PUBLICATION supabase_realtime ADD TABLE public.shift_timings;
EXCEPTION WHEN OTHERS THEN
    NULL;
END $$;

-- ------------------------------------------------------------------------------
-- 5. PROFILES TABLE PERMISSIONS & ROLE COLUMNS
-- ------------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'allowed_tabs') THEN
        ALTER TABLE public.profiles ADD COLUMN allowed_tabs JSONB DEFAULT '[]'::jsonb;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'role') THEN
        ALTER TABLE public.profiles ADD COLUMN role TEXT DEFAULT 'employee';
    END IF;
END $$;

